<?php echo $this->headScript()
            ->prependFile($this->basePath() . '/front/js/tinymce_script.js')
            ->prependFile($this->basePath() . '/front/vendor/tinymce/tinymce.min.js')
             ; ?>
<div class="page_heading_div two_column">
	<?php
		$title = 'Submit an Article';
		$this->headTitle($title);
	?>
	<h1><?php echo $this->escapeHtml($title); ?></h1>
	
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('frontarticles', array('action' => 'add')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	?>
	<input type="hidden" name="redirect" value="<?php echo $this->url('frontarticles', array('action' => 'mine')); ?>" />
	<div class="form_inner_div article_radio_choose <?php echo ($this->is_form_submitted)?'none_display':''?>" id="article_radio">
		<div class="big_radio <?php echo ($form->get('type')->getValue() == '' || $form->get('type')->getValue() == 'article')?'actv':''; ?>"><div class="big_radio_inner"></div></div>
		<strong>Article Submission</strong> - Article must be accepted by our editors for publication. Headlines appear on our partner websites.
	</div>
	<div class="form_inner_div article_radio_choose <?php echo ($this->is_form_submitted)?'none_display':''?>" id="blog_radio">
		<div class="big_radio <?php echo ($form->get('type')->getValue() != '' && $form->get('type')->getValue() == 'blog')?'actv':''; ?>"><div class="big_radio_inner"></div></div><strong>Blog Post</strong> - Your personal blog for anything stock market related. Blog posts are published instantly without requiring acceptance by our editors. Instablog headlines don't appear on partner sites.
	</div>
	<div class="form_inner_div <?php echo ($this->is_form_submitted)?'none_display':''?>" id="radio_submit">
		<input type="button" name="select_article_type" id="submitbutton" value="Click to continue" style="margin-top: 0px" />
	</div>
	
	<div class="form_inner_div <?php echo ($this->is_form_submitted)?'':'none_display'?>" id="add_form_div">
    	<div class="form_inner_div_left">
			<?php echo $this->formRow($form->get('article_id')); ?>
			<br>
			<?php echo $this->formRow($form->get('title')); ?>
			<br>
			<?php echo $this->formRow($form->get('alias')); ?>
			<br>
			<?php echo $this->formRow($form->get('short_description')); ?>
			<br>
			<?php echo $this->formRow($form->get('description')); ?>
			<br>
		</div>
		<div class="form_inner_div_right">
	    	<div class="none_display">
	    		<?php echo $this->formRow($form->get('type')); ?>
				<br>
			</div>
			<?php echo $this->formRow($form->get('source')); ?>
			<br>
			<div class="field_box">
				<textarea name="tags" id="tags" class="dnone"></textarea>
				<div style="position: relative">
					<div class="tags_box">
						<input type="text" name="tag_keyword" id="tag_keyword" placeholder="Type Tags"/>	
					</div>
					<div class="tag_option dnone" id="tag_options"></div>
				</div>
			</div>
			<br>
			<div class="field_box">
		    	<label>Select Categories:</label>
		    
		    	<div class="muti_checkboxes">
		        	<?php echo $this->dynamic_options['categories_checkboxes']; ?>
		        </div>
			</div>
			<br>
			<?php echo $this->formRow($form->get('image')); ?>
    	</div>
    	<div class="clearfix"></div>
    	<?php echo $this->formSubmit($form->get('submit')); ?>
    	<input type="button" id="go_choose_article_type" class="submitbutton" value="Back to Choose Type" />
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>