
<div class="user_profile_section">
	
	<div class="article_listing_section">
    <div class="tab_heading">Articles</div>
	<div class="row-fluid padding-allsides">
		<?php 
		$count_article = 0;
		foreach ($articles as $article)
		{
			$diff_time =  (($article->date_created)?(time()-strtotime($article->date_created)):0);
			$days = (int)($diff_time/(3600*24));
			if($diff_time <= 60)
			{
				$past_time_text = (int)$diff_time." Seconds";
			}
			elseif($diff_time <= 60*60)
			{
				$past_time_text = (int)($diff_time/60)." Minutes";
			}
			elseif($diff_time <= 60*60*24)
			{
				$past_time_text = (int)($diff_time/(60*60))." Hours";
			}
			elseif($days <= 7)
			{
				$past_time_text = (int)$days." Days";
			}
			elseif($days >= 7 && $days < 30)
			{
				$past_time_text = (int)($days/7)." weeks";
			}
			elseif($days >= 30 && $days < 365)
			{
				$past_time_text = (int)($days/30)." months";
			}
			elseif($days >= 365)
			{
				$past_time_text = (int)($days/365)." years";
			}
			
			$author 				= $authors[$article->author_id];
			$author_username 		= $authors_usernames[$article->author_id];
			$author_articles_count 	= isset($user_articles_count[$article->author_id])?$user_articles_count[$article->author_id]:0;
				
			if($count_article % 2 == 0 && $count_article != 0)
			{
				?>
				</div><div class="row-fluid padding-allsides">
				<?php
			}
			
			$user_image = ($article->user_image == '')?IMAGE_URL.'user_image.png':MEMBER_IMAGE_URL.$article->user_image;
			$count_article++;
			?>
			<div class="span12">
	        	<?php /*?><div class="month left">
	            	<span><?php echo date('M', strtotime($article->date_created));?></span>
	                <span><?php echo date('Y', strtotime($article->date_created));?></span>
	            </div><?php */?>
                
	             <div class="month_description">
                <div class="month_description_img">
	            	<img src="<?php echo $user_image; ?>" alt="user_image">
                    </div>
                    <div class="month_description_content">
	            	
	            	<a href="<?php echo HOME_URL.'article/'.$article->alias;?>"><?php echo substr(strip_tags($article->title), 0, 62).((strlen($article->title)>62)?"...":'');?></a>
	            	<p><?php echo substr(strip_tags($article->description), 0, 120).((strlen($article->description)>120)?"...":'');?></p>
	                <ul class="monthdescription_listing">
	                	<li><i class="fa fa-clock-o"></i> &nbsp;<?php echo $past_time_text;?> ago</li>
	                	<?php 
	                	if($article->source != '')
	                	{
	                		?>
	                    	<li><a href="<?php echo (strstr($article->source, 'http://')?$article->source:'http://'.$article->source);?>"><i class="fa fa-folder-open"></i> &nbsp; Source</a></li>
	                    	<?php 
	                	}
	                	?>
	                    <li><i class="fa fa-user"></i> &nbsp; Author: <a href="<?php echo HOME_URL.'portfolio/'.$author_username;?>"><?php echo $author?>(<?php echo $author_articles_count?> Articles)</a></li>
	                </ul>
                    </div>
	            </div>
	        </div>
	        <?php 
		}
		?>
	</div>
    <div class="readmore"><a href="<?php echo $this->url('frontarticles', array('action'=> 'all'));?>" class="yellow_btn">read more &raquo;</a></div>
    </div>
        <div class="rightsidebar">
    <div class="new_section nsd">
    <h2>News</h2>
    <div class="new_section_row">
    <div class="month_description_content">
	 <a href="http://www.8edge.co/#">Test News</a>
	 <p>Lorem Ipsum is simply dummy  </p>
	 <ul class="monthdescription_listing">
	
	 
	 </ul>
     </div>
</div>
    <div class="new_section_row">
    <div class="month_description_content">
	 <a href="http://www.8edge.co/#">Test News</a>
	 <p>Lorem Ipsum is simply dummy  </p>
	 <ul class="monthdescription_listing">
	
	 
	 </ul>
     </div>
</div>
    <div class="new_section_row">
    <div class="month_description_content">
	 <a href="http://www.8edge.co/#">Test News</a>
	 <p>Lorem Ipsum is simply dummy  </p>
	 <ul class="monthdescription_listing">
	 
	 
	 </ul>
     </div>
</div>
    <div class="new_section_row">
    <div class="month_description_content">
	 <a href="http://www.8edge.co/#">Test News</a>
	 <p>Lorem Ipsum is simply dummy  </p>
	 <ul class="monthdescription_listing">
	 
	 
	 </ul>
     </div>
</div>
    <div class="new_section_row">
    <div class="month_description_content">
	 <a href="http://www.8edge.co/#">Test News</a>
	 <p>Lorem Ipsum is simply dummy  </p>
	 <ul class="monthdescription_listing">
	
	 
	 </ul>
     </div>
</div>





                    
    
    
    
    </div>
    
    </div>
</div>
<div class="clearfix"></div>