<?php 
echo $this->partial('application/partials/articles_listing_with_cats.phtml', 
	array(
		'paginator' => $paginator,
		'articles' 	=> $articles,
		'categories'=> $categories,
		'cat'		=> $cat,
		'sub_cat'	=> $sub_cat,
		'user'		=> $user,
		'user_articles_count' 	=> $user_articles_count,
		'authors' 				=> $authors,
		'authors_usernames' 	=> $authors_usernames,
		'cur_page_no'			=> $cur_page_no,
		'category'				=> $category,
	)
); 
?>