<div id="article_categories" class="article_categories">
	<ul>
		<!-- <li><a href="<?php echo HOME_URL;?>articles/all" class="<?php echo ($cat == 'all' || $cat == '')?'active':''?>">All</a></li> -->
		<?php
		$p_count = 0;
		foreach($categories as $category)
		{
			$parent_alias = $category->alias;
			?>
			<li>
				<a href="<?php echo HOME_URL;?>articles/all/<?php echo $parent_alias; ?>" class="<?php echo ($cat == $parent_alias)?'active':''?> "><?php echo $category->name;?></a>
				<ul id="subcat_<?php echo $category->alias; ?>" class="<?php echo ($cat == '' && $p_count == 0)?'':(($cat == $parent_alias)?'':'dnone'); ?> sub_cat">
					<!-- <li><a href="<?php echo HOME_URL;?>articles/all" class="<?php echo ($cat == '')?'active':''?>">All</a></li> -->
					<?php
					$s_count = 0;
					foreach($category->children as $sub_category)
					{
						?>
						<li>
							<a href="<?php echo HOME_URL;?>articles/all/<?php echo $parent_alias; ?>/<?php echo $sub_category->alias; ?>" class="<?php echo ($sub_cat == $sub_category->alias)?'active':''?> "><?php echo $sub_category->name;?></a>
						</li>
						<?php
					} 
					$s_count++;
					?>
				</ul>
			</li>
			<?php
			$p_count++;
		} 
		?>
	</ul>
</div>
<div class="cboth"></div>
<div class="articles_listing">
	
<div class="tab_heading">Articles</div>
	
	<div class="row-fluid padding-allsides">
		<?php 
		$count_article = 0;
		foreach ($this->paginator as $article)
		{
			$diff_time =  (($article->date_created)?(time()-strtotime($article->date_created)):0);
			$days = (int)($diff_time/(3600*24));
			if($diff_time < 60)
			{
				$past_time_text = (int)$diff_time." Seconds";
			}
			elseif($diff_time < 60*60)
			{
				$past_time_text = (int)($diff_time/60)." Minutes";
			}
			elseif($diff_time < 60*60*24)
			{
				$past_time_text = (int)($diff_time/(60*60))." Hours";
			}
			elseif($days < 7)
			{
				$past_time_text = (int)$days." Days";
			}
			elseif($days > 7 && $days < 30)
			{
				$past_time_text = (int)($days/7)." weeks";
			}
			elseif($days > 30 && $days < 365)
			{
				$past_time_text = (int)($days/30)." months";
			}
			elseif($days > 365)
			{
				$past_time_text = (int)($days/365)." years";
			}
			
			
			if($count_article % 2 == 0 && $count_article != 0)
			{
				?>
				</div><div class="row-fluid padding-allsides">
				<?php
			}
			$count_article++;
			?>
			<div class="span12">
	       <?php /*?> 	<div class="month left">
	            	<span><?php echo date('M', strtotime($article->date_created));?></span>
	                <span><?php echo date('Y', strtotime($article->date_created));?></span>
	            </div><?php */?>
	            <div class="month_description">
                <div class="month_description_img">
	            	<img src="http://www.8edge.co/front/img/user_image.png" alt="user_image">
                    </div>
                    <div class="month_description_content">
	            	<h2><a href="<?php echo HOME_URL.'article/'.$article->alias;?>"><?php echo substr(strip_tags($article->title), 0, 62).((strlen($article->title)>62)?"...":'');?></a></h2>
                    <p><?php echo substr(strip_tags($article->description), 0, 120).((strlen($article->description)>120)?"...":'');?></p>
	                <ul class="monthdescription_listing">
	                	<li><?php echo $past_time_text;?> ago</li>
	                    <li><a href="<?php echo (strstr($article->source, 'http://')?$article->source:'http://'.$article->source);?>">Source</a></li>
	                </ul>
                    </div>
	            </div>
	        </div>
	        <?php 
		}
		?>
	</div>
    <?php
	// add at the end of the file after the table
	echo $this->paginationControl(
	// the paginator object
	$this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'article'),
	    // the route to link to when a user clicks a control link
	    array(
	    	'route' => 'frontarticles',
			'action'=> 'all/',
	    )
	);
	?>
</div>
<div class="clearfix"></div>