<?php echo $this->headScript()
            ->prependFile($this->basePath() . '/front/js/tinymce_script.js')
            ->prependFile($this->basePath() . '/front/vendor/tinymce/tinymce.min.js')
             ; ?>
<div class="page_heading_div two_column">
	<?php
		$title = ($article->meta_title == '')?'Edit Article '.$article->title:$article->meta_title;
		$this->headTitle($title);
	?>
	<h1>
	<?php 
		$page_heading = 'Edit Article <span>"'.$article->title.'"</span>';
		echo $page_heading; 
	?>
	</h1>
	
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('frontarticles', array('action' => 'edit', 'article_id'     => $this->article_id,)));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	?>
	<input type="hidden" name="redirect" value="<?php echo $this->url('frontarticles', array('action' => 'mine')); ?>" />
	<div class="form_inner_div" id="add_form_div">
    	<div class="form_inner_div_left">
			<?php echo $this->formRow($form->get('article_id')); ?>
			<br>
			<?php echo $this->formRow($form->get('title')); ?>
			<br>
			<?php echo $this->formRow($form->get('alias')); ?>
			<br>
			<?php echo $this->formRow($form->get('short_description')); ?>
			<br>
			<?php echo $this->formRow($form->get('description')); ?>
			<br>
		</div>
		<div class="form_inner_div_right">
	    	<div class="none_display">
	    		<?php echo $this->formRow($form->get('type')); ?>
				<br>
			</div>
			<?php echo $this->formRow($form->get('source')); ?>
			<br>
			<div class="field_box">
				<?php 
				$tag_field = $form->get('tags');
				$tags = $tag_field->getValue();
				?>
				<textarea name="tags" id="tags" class="dnone"><?php echo $tags;?></textarea>
				<div style="position: relative">
					<div class="tags_box">
						<?php
						foreach(explode(', ', trim($tags, ', ')) as $tag)
						{
							?>
							<div class="tags" rel="tag__<?php echo $tag; ?>"><?php echo $tag; ?><span class="remove_tag">x</span></div>
							<?php
						} 
						?>
						<input type="text" name="tag_keyword" id="tag_keyword" placeholder="Type Tags"/>	
					</div>
					<div class="tag_option dnone" id="tag_options"></div>
				</div>
			</div>
			<br>
			<div class="field_box">
		    	<label>Select Categories:</label>
		    
		    	<div class="muti_checkboxes">
		        	<?php echo $this->dynamic_options['categories_checkboxes']; ?>
		        </div>
			</div>
			<br>
			<div class="field_box">
				<?php 
				$image_field = $form->get('image');
				echo $this->formRow($image_field);
				//$img_val = $image_field->getValue());
				
				if($image_field->getValue() != '')
				{
					?>
					<img width="75px" height="75px" src="<?php echo ARTICLE_IMAGE_URL.$image_field->getValue();?>" />
					<input value="1" type="checkbox" style="disply: inline; margin: 0 0  0 30px; width: 20px; height: 0px" name="del_image" id="del_image">Remove Image
					<?php
				}
				?>
			</div>
    	</div>
    	<div class="clearfix"></div>
    	<?php echo $this->formSubmit($form->get('submit')); ?>
    	<input type="button" id="go_choose_article_type" class="submitbutton" value="Back to Choose Type" />
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
