<div style="margin: 0px auto 110px; text-align: center; color: #777; width: 650px;">
	<h2>Thanks, Article/Blog has been successfully saved as draft.</h2> 
	<h5 style="margin-bottom: 25px; margin-top: 40px;">It will not be sent to the editor for review untill you complete all the steps of article submission.</h5>
	<p>You can complete this article anytime by going to menu <a href="<?php echo $this->url('frontarticles', array('action' => 'mine')); ?>">Manage Articles</a>.</p>
</div>