<style>
.arrows{
    float: right;
}
</style>


<h1 class="guidelines_heading topic">Article  Guidelines</h1>
  <div class="2ndul">
	<div class="guide_lines" id="guide_lines" style="">
		<h1>Title:</h1>
		<ul>
			<li>Express clearly the article's key objectives.</li>
			<li>If your article about one stock, mention in the title.</li>
			<li>Do not include ticker symbols in titles.</li>
		</ul>
		<h1>Summary:</h1>
		<ul>
			<li>Summaries are mandatory and allow the reader to easily grasp the key points.</li>
			<li>A minimum of 3 bullets and maximum of 5 are allowed for all articles.</li>
			
		</ul>
		<h1>Article:</h1>
		<ul>
			<li>Please proofread and spellcheck.</li>
			<li>Hyperlink all source materials.</li>
			<li>The first mention of a stock/ETF should be followed by its ticker - for example, CheungKong(Holdings) Ltd (0001.HK). Currently, we support HK and Singapore tickers only.</li>
			<li>Stocks/ETFs symbol must be mentioned in the article if you want the headline to appear on the symbol's main pages.</li>

		</ul>
		<h1>Pictures / Images:</h1>
		<ul>
			<li>To upload image save the image separately and upload. </li>
			<li>Maximum Image Size 10MB</li>
			<li>Maximum Image Dimensions 1300x1000</li>
			<li>Allowed Image Format .gif, .jpg and .png</li>
		</ul>
		</div>
	</div>