<html>
<head></head>
<body style="margin: 0px; padding: 0px;">
	<div class="login_popup_box">
		<section id="content">
			<form action="">
				<h1>Join now (it's free):</h1>
				<div>
					<input type="text" placeholder="Choose Username" required id="username" />
				</div>
	            <div>
					<input type="email" placeholder="Email Address" required id="username" />
				</div>
	            
				<div>
					<input type="password" placeholder="Password" required id="password" />
				</div>
				<div>
					<input type="submit" value="Join" />
				
				</div>
			</form><!-- form -->
	
		</section><!-- content -->
	    
	    <section id="content" style=" margin-left:30px;">
			<form action="">
				<h1>Member sign in:</h1>
				<div>
					<input type="text" placeholder="Username" required id="username" />
				</div>
				<div>
					<input type="password" placeholder="Password" required id="password" />
				</div>
				<div>
					<input type="submit" value="Sign in" />
					<a href="#">Lost your password?</a>
				</div>
	            <div>
					<input type="submit" value="Sign in with linkedin" />
				</div>
			</form><!-- form -->
	
		</section><!-- content -->
	</div><!-- container -->
	<style>
	.left { float:left; }
	.right { float:right; }
	.alignleft { float: left; margin-right: 15px; }
	.alignright { float: right; margin-left: 15px; }
	.clearfix:after,
	form:after {
		content: ".";
		display: block;
		height: 0;
		clear: both;
		visibility: hidden;
	}
	.login_popup_box{ float:left;position: relative; padding:20px; background:#eee; }
	#content {
		background: #f9f9f9;
		background: -moz-linear-gradient(top,  rgba(248,248,248,1) 0%, rgba(249,249,249,1) 100%);
		background: -webkit-linear-gradient(top,  rgba(248,248,248,1) 0%,rgba(249,249,249,1) 100%);
		background: -o-linear-gradient(top,  rgba(248,248,248,1) 0%,rgba(249,249,249,1) 100%);
		background: -ms-linear-gradient(top,  rgba(248,248,248,1) 0%,rgba(249,249,249,1) 100%);
		background: linear-gradient(top,  rgba(248,248,248,1) 0%,rgba(249,249,249,1) 100%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f8f8f8', endColorstr='#f9f9f9',GradientType=0 );
		-webkit-box-shadow: 0 1px 0 #fff inset;
		-moz-box-shadow: 0 1px 0 #fff inset;
		-ms-box-shadow: 0 1px 0 #fff inset;
		-o-box-shadow: 0 1px 0 #fff inset;
		box-shadow: 0 1px 0 #fff inset;
		border: 1px solid #c4c6ca; float:left;
		padding: 25px 0 0;
		position: relative;
		text-align: center;
		text-shadow: 0 1px 0 #fff;
		width:300px;
	}
	#content h1 {
		color: #7E7E7E;
		font:18px Helvetica, Arial, sans-serif;
		line-height: 20px;
		margin: 10px 0 20px;
	}
	
	#content form { margin: 0 20px; position: relative }
	#content form input[type="text"],
	#content form input[type="password"], #content form input[type="email"] {
		-webkit-border-radius: 3px;
		-moz-border-radius: 3px;
		-ms-border-radius: 3px;
		-o-border-radius: 3px;
		border-radius: 3px;
		-webkit-box-shadow: 0 1px 0 #fff, 0 -2px 5px rgba(0,0,0,0.08) inset;
		-moz-box-shadow: 0 1px 0 #fff, 0 -2px 5px rgba(0,0,0,0.08) inset;
		-ms-box-shadow: 0 1px 0 #fff, 0 -2px 5px rgba(0,0,0,0.08) inset;
		-o-box-shadow: 0 1px 0 #fff, 0 -2px 5px rgba(0,0,0,0.08) inset;
		box-shadow: 0 1px 0 #fff, 0 -2px 5px rgba(0,0,0,0.08) inset;
		-webkit-transition: all 0.5s ease;
		-moz-transition: all 0.5s ease;
		-ms-transition: all 0.5s ease;
		-o-transition: all 0.5s ease;
		transition: all 0.5s ease;
		background: #eae7e7 url(http://cssdeck.com/uploads/media/items/8/8bcLQqF.png) no-repeat;
		border: 1px solid #c8c8c8;
		color: #777;
		font: 13px Helvetica, Arial, sans-serif;
		margin: 0 0 10px;
		padding: 15px 10px 15px 40px;
		width: 80%;
	}
	#content form input[type="text"]:focus,
	#content form input[type="password"]:focus,  #content form input[type="email"]:focus  {
		-webkit-box-shadow: 0 0 2px #ed1c24 inset;
		-moz-box-shadow: 0 0 2px #ed1c24 inset;
		-ms-box-shadow: 0 0 2px #ed1c24 inset;
		-o-box-shadow: 0 0 2px #ed1c24 inset;
		box-shadow: 0 0 2px #ed1c24 inset;
		background-color: #fff;
		border: 1px solid #ed1c24;
		outline: none;
	}
	#username { background-position: 10px 10px !important }
	#password { background-position: 10px -53px !important }
	#content form input[type="submit"] {
		background: rgb(254,231,154);
		background: -moz-linear-gradient(top,  rgba(254,231,154,1) 0%, rgba(254,193,81,1) 100%);
		background: -webkit-linear-gradient(top,  rgba(254,231,154,1) 0%,rgba(254,193,81,1) 100%);
		background: -o-linear-gradient(top,  rgba(254,231,154,1) 0%,rgba(254,193,81,1) 100%);
		background: -ms-linear-gradient(top,  rgba(254,231,154,1) 0%,rgba(254,193,81,1) 100%);
		background: linear-gradient(top,  rgba(254,231,154,1) 0%,rgba(254,193,81,1) 100%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fee79a', endColorstr='#fec151',GradientType=0 );
		-webkit-border-radius: 30px;
		-moz-border-radius: 30px;
		-ms-border-radius: 30px;
		-o-border-radius: 30px;
		border-radius: 30px;
		-webkit-box-shadow: 0 1px 0 rgba(255,255,255,0.8) inset;
		-moz-box-shadow: 0 1px 0 rgba(255,255,255,0.8) inset;
		-ms-box-shadow: 0 1px 0 rgba(255,255,255,0.8) inset;
		-o-box-shadow: 0 1px 0 rgba(255,255,255,0.8) inset;
		box-shadow: 0 1px 0 rgba(255,255,255,0.8) inset;
		border: 1px solid #D69E31;
		color: #85592e;
		cursor: pointer;
		float: left;
		font: bold 15px Helvetica, Arial, sans-serif;
		height: 35px;
		margin: 10px 0 10px 0px;
		position: relative;
		text-shadow: 0 1px 0 rgba(255,255,255,0.5);
		min-width: 120px;
	}
	#content form input[type="submit"]:hover {
		background: rgb(254,193,81);
		background: -moz-linear-gradient(top,  rgba(254,193,81,1) 0%, rgba(254,231,154,1) 100%);
		background: -webkit-linear-gradient(top,  rgba(254,193,81,1) 0%,rgba(254,231,154,1) 100%);
		background: -o-linear-gradient(top,  rgba(254,193,81,1) 0%,rgba(254,231,154,1) 100%);
		background: -ms-linear-gradient(top,  rgba(254,193,81,1) 0%,rgba(254,231,154,1) 100%);
		background: linear-gradient(top,  rgba(254,193,81,1) 0%,rgba(254,231,154,1) 100%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fec151', endColorstr='#fee79a',GradientType=0 );
	}
	#content form div a {
		color: #004a80;
	    float: right;
	    font-size: 12px;
	    margin:18px 15px 0 0;
	    text-decoration: underline;
	}
	.button {
		background: rgb(247,249,250);
		background: -moz-linear-gradient(top,  rgba(247,249,250,1) 0%, rgba(240,240,240,1) 100%);
		background: -webkit-linear-gradient(top,  rgba(247,249,250,1) 0%,rgba(240,240,240,1) 100%);
		background: -o-linear-gradient(top,  rgba(247,249,250,1) 0%,rgba(240,240,240,1) 100%);
		background: -ms-linear-gradient(top,  rgba(247,249,250,1) 0%,rgba(240,240,240,1) 100%);
		background: linear-gradient(top,  rgba(247,249,250,1) 0%,rgba(240,240,240,1) 100%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f7f9fa', endColorstr='#f0f0f0',GradientType=0 );
		-webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.1) inset;
		-moz-box-shadow: 0 1px 2px rgba(0,0,0,0.1) inset;
		-ms-box-shadow: 0 1px 2px rgba(0,0,0,0.1) inset;
		-o-box-shadow: 0 1px 2px rgba(0,0,0,0.1) inset;
		box-shadow: 0 1px 2px rgba(0,0,0,0.1) inset;
		-webkit-border-radius: 0 0 5px 5px;
		-moz-border-radius: 0 0 5px 5px;
		-o-border-radius: 0 0 5px 5px;
		-ms-border-radius: 0 0 5px 5px;
		border-radius: 0 0 5px 5px;
		border-top: 1px solid #CFD5D9;
		padding: 15px 0;
	}
	.button a {
		background: url(http://cssdeck.com/uploads/media/items/8/8bcLQqF.png) 0 -112px no-repeat;
		color: #7E7E7E;
		font-size: 17px;
		padding: 2px 0 2px 40px;
		text-decoration: none;
		-webkit-transition: all 0.3s ease;
		-moz-transition: all 0.3s ease;
		-ms-transition: all 0.3s ease;
		-o-transition: all 0.3s ease;
		transition: all 0.3s ease;
	}
	.button a:hover {
		background-position: 0 -135px;
		color: #00aeef;
	}
	</style>
</body>
</html>