<div class="user_portfolio_section">
	<?php
	$memeber_name = ($member->display_name == '')?$member->first_name.' '.$member->first_name:$member->display_name;
	?>
    <div class="user_profile_section">
		<div class="ups_leftside">
			<?php 
				echo $this->partial('application/partials/portfolio_left_column.phtml', 
					array(
						'member' 				=> $member,
        				'user_articles_count' 	=> $user_articles_count,
						'user_blogs_count' 		=> $user_blogs_count,
						'user_comments_count'	=> $user_comments_count,
						'followed_status'		=> $followed_status,
						'followerCount'			=> $followerCount,
						'followedCount'			=> $followedCount,
						)
				); 
			?>
		</div>
		<div class="ups_rightside">
			<div class="ups_rightside_row">
				<div class="ups_rightside_head">
					<h5>About</h5>
					<!-- <div class="ups_edit">
						<a href="#">&nbsp;</a>
					</div> -->
				</div>
				<p><?php echo ($member->about == '')?'Currently, No infomation added about the user.':$member->about; ?></p>
			</div>
			<div class="ups_rightside_row">
				<div class="ups_rightside_head">
					<h5>Company</h5>
					<!-- <div class="ups_edit">
						<a href="#">&nbsp;</a>
					</div> -->
				</div>
				<p><?php echo ($member->company == '')?'Currently, No company profile added.':$member->company; ?></p>
			</div>
			<div class="ups_rightside_row">
				<div class="ups_rightside_head">
					<h5>Articles</h5>
					<?php 
					if($user_articles_count > 5)
					{
						?>
						<a href="<?php echo HOME_URL . 'articles/all/user/'.$member->username; ?>" class="fright"> more &gt;&gt;</a>
						<?php
					}
					?>
				</div>
				<div>
					<ul>
						<?php 
						foreach($articles as $article)
						{
							?>
							<li><?php echo $article->title;?></li>
							<?php
						}
						?>
					</ul>
				</div>
			</div>
			
			<div class="ups_rightside_row">
				<div class="ups_rightside_head">
					<h5>Blog Posts</h5>
					<?php 
					if($user_blogs_count > 5)
					{
						?>
						<a href="<?php echo HOME_URL . 'blogs/all/user/'.$member->username; ?>" class="fright"> more &gt;&gt;</a>
						<?php
					}
					?>
				</div>
				<div>
					<ul>
						<?php 
						foreach($blogs as $blog)
						{
							?>
							<li><?php echo $blog->title;?></li>
							<?php
						}
						?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>