<?php
if(count($this->search_options) > 0)
{
	?>
	<ul>
		<?php 
		foreach($this->search_options as $search_option_label => $search_option)
		{
			$count =  0;
			foreach($search_option as $option)
			{
				if($count++ >= 5)
					break;
				?>
				<li id="<?php echo $option['tag']; ?>" class="select_tag"><?php echo $option['label']; ?></li>
				<?php 
			}
		}
		?>
	</ul>
	<?php
}
else
{
	echo '';	
}